---
  - name: Install dependencies
    become: True
    when: dns_store_ssh_fingerprint | bool and ansible_distribution == "Debian"
    apt:
      state: present
      update_cache: yes
      cache_valid_time: 1800
      name:
        - dnsutils

  - name: Install dependencies
    become: True
    when: dns_store_ssh_fingerprint | bool and ansible_distribution == "Archlinux"
    package:
      state: present
      name:
        - bind-tools

  - name: Upload DNS SSHFP script
    become: True
    when: dns_store_ssh_fingerprint | bool
    template:
      src: hostkeys.sh.j2
      dest: /etc/ssh/dns.sh
      owner: root
      group: root
      mode: 0744

  - name: Push SSHFP to DNS
    become: True
    when: dns_store_ssh_fingerprint | bool
    command: /etc/ssh/dns.sh
    args:
      creates: /etc/ssh/.dns

  - name: Upload dynamic_dns script
    become: True
    when: dns_do_dynamic_dns | bool
    template:
      src: dynamic_dns.sh.j2
      dest: /usr/local/bin/dynamic_dns.sh
      owner: root
      group: root
      mode: 0755

  - name: Create systemd service and timer for dynamic_dns
    become: True
    when: dns_do_dynamic_dns | bool
    copy:
      src: "{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    notify: reload dynamic_dns
    with_items:
      - dynamic-dns.service
      - dynamic-dns.timer
